export const CARS = [
  {
    brand: 'Ferrari',
    models: [
      'SF90 Stradale',
      'SF90 Spider',
      '812 Superfast',
      '812 GTS',
      'F8 Tributo',
      'F8 Spider',
      'Roma',
      '296 GTB',
      '458 Italia',
      'LaFerrari',
    ],
  },
  {
    brand: 'Lamborghini',
    models: [
      'Aventador',
      'Aventador SVJ',
      'Huracán',
      'Huracán EVO',
      'Huracán STO',
      'Revuelto',
      'Urus',
      'Gallardo',
      'Murciélago',
      'Sian',
    ],
  },
  {
    brand: 'Porsche',
    models: [
      '911 Carrera',
      '911 Turbo S',
      '911 GT3',
      '911 GT3 RS',
      '911 GT2 RS',
      '718 Cayman',
      '718 Boxster',
      'Taycan Turbo S',
      'Panamera Turbo',
      'Carrera GT',
    ],
  },
  {
    brand: 'McLaren',
    models: [
      '720S',
      '720S Spider',
      '750S',
      '765LT',
      '570S',
      '600LT',
      'Artura',
      'GT',
      'P1',
      'Senna',
    ],
  },
  {
    brand: 'Bugatti',
    models: [
      'Veyron',
      'Veyron Super Sport',
      'Chiron',
      'Chiron Sport',
      'Chiron Super Sport',
      'Chiron Pur Sport',
      'Divo',
      'Centodieci',
      'Mistral',
      'Bolide',
    ],
  },
  {
    brand: 'Aston Martin',
    models: [
      'DB11',
      'DB12',
      'DBS Superleggera',
      'Vantage',
      'Vantage F1 Edition',
      'Vanquish',
      'Valhalla',
      'Valkyrie',
      'One-77',
      'Rapide',
    ],
  },
  {
    brand: 'Pagani',
    models: [
      'Zonda',
      'Zonda F',
      'Zonda Cinque',
      'Huayra',
      'Huayra BC',
      'Huayra Roadster',
      'Huayra R',
      'Utopia',
      'Utopia Roadster',
      'Zonda Revolución',
    ],
  },
  {
    brand: 'Koenigsegg',
    models: [
      'Agera',
      'Agera RS',
      'Regera',
      'Jesko',
      'Jesko Absolut',
      'Gemera',
      'CCX',
      'CCR',
      'One:1',
      'CC850',
    ],
  },
  {
    brand: 'Mercedes-AMG',
    models: [
      'AMG GT',
      'AMG GT S',
      'AMG GT R',
      'AMG GT Black Series',
      'C63 AMG',
      'E63 AMG',
      'S63 AMG',
      'CLS 63 AMG',
      'SL 63 AMG',
      'G 63 AMG',
    ],
  },
  { brand: 'BMW', models: ['M2', 'M3', 'M4', 'M5', 'M8', 'i8', 'Z4', 'X5 M', 'X6 M', '3 Series'] },
  {
    brand: 'Audi',
    models: ['R8', 'RS7', 'RS6 Avant', 'RS5', 'RS3', 'S8', 'A8', 'A6', 'Q8', 'TT RS'],
  },
  {
    brand: 'Nissan',
    models: [
      'GT-R',
      'GT-R Nismo',
      '370Z',
      '350Z',
      'Z',
      'Silvia S15',
      'Skyline R34',
      'Skyline R32',
      'Fairlady Z',
      'Maxima',
    ],
  },
  {
    brand: 'Toyota',
    models: [
      'Supra MK4',
      'Supra MK5',
      'GR86',
      'GT86',
      'GR Yaris',
      'Land Cruiser 300',
      'Land Cruiser Prado',
      'Camry',
      'Corolla',
      'Mark II',
    ],
  },
  {
    brand: 'Honda',
    models: [
      'NSX',
      'NSX Type S',
      'Civic Type R',
      'Civic',
      'Accord',
      'Integra Type R',
      'S2000',
      'Prelude',
      'CR-V',
      'Fit',
    ],
  },
  {
    brand: 'Ford',
    models: [
      'GT',
      'Mustang GT',
      'Mustang Shelby GT500',
      'Mustang Mach-E',
      'F-150 Raptor',
      'Focus RS',
      'Fiesta ST',
      'Explorer',
      'Bronco',
      'Fusion',
    ],
  },
] as const;
